# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- main

# pool:
#  vmImage: 'windows-latest'
pool:
  name: 'Default'
  demands:
    - Agent.Version -gtVersion 4.260.0
    - java

variables:
  solution: 'Stage-02-new-architecture/Src/AssetTracker.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:
- task: NuGetToolInstaller@1

- task: NuGetCommand@2
  inputs:
    command: 'restore'
    restoreSolution: 'Stage-02-new-architecture\Src\AssetTracker.sln'
    feedsToUse: 'select'

- task: SonarCloudPrepare@3
  inputs:
    SonarQube: 'SonarQubeCloud'
    organization: 'paweltruong'
    scannerMode: 'dotnet'
    projectKey: 'paweltruong_AssetTracker'
    projectName: 'AssetTracker'
    extraProperties: |
      # Additional properties that will be passed to the scanner, 
      # Put one key=value per line, example:
      # sonar.exclusions=**/*.bin
      sonar.coverage.exclusions=**/Migrations/**
      sonar.exclusions=Stage-01-poc/**
      sonar.tests=**/Tests/**,**/*Test*
      sonar.test.exclusions=**/obj/**,**/bin/**
      sonar.dotnet.exclude.temporary.projects=false
      sonar.cs.vstest.reportsPaths=$(Agent.TempDirectory)/**/*.trx
      sonar.cs.opencover.reportsPaths=$(Agent.TempDirectory)/**/coverage.opencover.xml

# 2. Restore NuGet packages
- task: DotNetCoreCLI@2
  displayName: 'Restore NuGet packages'
  inputs:
    command: 'restore'
    projects: '$(solution)'
    
# 3. Build the solution (including WPF)
- task: DotNetCoreCLI@2
  displayName: 'Build solution'
  inputs:
    command: 'build'
    projects: '$(solution)'
    arguments: '--configuration $(buildConfiguration) --no-restore --verbosity normal'
    
# 4. Run tests with coverage
- task: DotNetCoreCLI@2
  displayName: 'Run tests with coverage'
  inputs:
    command: 'test'
    projects: 'Stage-02-new-architecture/Src/AssetTracker.Application.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage" --settings Stage-02-new-architecture/Src/coverage.runsettings --logger trx;LogFileName=ApplicationTests.trx'
    publishTestResults: true

- task: DotNetCoreCLI@2
  displayName: 'Run tests with coverage'
  inputs:
    command: 'test'
    projects: 'Stage-02-new-architecture/Src/AssetTracker.AssetsImporter.Steam.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage" --settings Stage-02-new-architecture/Src/coverage.runsettings --logger trx;LogFileName=AssetsImporterSteamTests.trx'
    publishTestResults: true

- task: DotNetCoreCLI@2
  displayName: 'Run tests with coverage'
  inputs:
    command: 'test'
    projects: 'Stage-02-new-architecture/Src/AssetTracker.AssetsResolver.HumbleBundle.Tests.csproj'
    arguments: '--configuration $(buildConfiguration) --no-build --collect:"XPlat Code Coverage" --settings Stage-02-new-architecture/Src/coverage.runsettings --logger trx;LogFileName=AssetsResolverHumbleBundleTests.trx'
    publishTestResults: true
- task: SonarCloudAnalyze@3
  inputs:
    jdkversion: 'JAVA_HOME'

- task: SonarCloudPublish@3
  inputs:
    pollingTimeoutSec: '300'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Coverage Reports'
  inputs:
    PathtoPublish: '$(Agent.TempDirectory)'
    ArtifactName: 'CoverageReports'
    publishLocation: 'Container'